<?php

namespace App\Repository;

/**
 * ContactRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Count all contacts.
     *
     * @return int
     */
    public function countAllContact()
    {
        $query = $this->_em
            ->createQuery("SELECT count(c) FROM App:Contact c");

        return (int) $query->getSingleScalarResult();
    }
}
