<?php

namespace App\Repository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Count all users.
     *
     * @return int
     */
    public function countAllUser()
    {
        $query = $this->_em
            ->createQuery("SELECT count(u) FROM App:User u");

        return (int) $query->getSingleScalarResult();
    }
}
